### ISSUE TITLE
gridsite.org is not working anymore

### ISSUE THREAD

**Issue by alvarolopez** [CESNET/gridsite#37]

**Comment by sustr4** [comment]
Hello, Alvaro, you are right. The original author of gridsite wished to keep the domain. The Web site has been inactive for some time but our registrar still reports the domain as taken.
Since we took over the maintenance in 2010 the contents of the original site have been cloned here:
https://wiki.metacentrum.cz/gswiki
And of course this GitHub repo is also a good contact point.

**Comment by alvarolopez** [comment]
Hi @sustr4, yes, but what I mean is that the README still shows the gridsite.org :-)

**Comment by valtri** [comment]
Gridsite release 2.3.5 tagged, with the updated URL.
